source 'https://rubygems.org'


gem 'rails', '4.2.1'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'thin'
gem 'rails_admin'
gem 'rails_12factor'
gem 'stripe'
gem 'devise'

group :development, :test do

gem 'byebug'
gem 'pry-rails'
gem 'pry-byebug'
gem 'rack-cors', :require => 'rack/cors'
gem 'web-console', '~> 2.0'
gem 'spring'
gem 'binding_of_caller'
gem 'better_errors'
end
