source 'https://rubygems.org'


gem 'rails', '4.2.1'
gem 'turbolinks'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'rails_12factor'
gem 'thin'
gem 'jquery-rails'
gem 'rails-api'
gem 'rack-cors', :require => 'rack/cors'
gem 'spring', :group => :development

gem 'pg'

gem 'pry-rails'
gem 'pry-byebug'


# To use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
